// tools/widgets-cli/templates/solid/src/App.tsx
import { createSignal } from 'solid-js';
import { setupDarkModeManagerMisc, useStyles, DarkModeManagerContext } from '@lenovo-it/widgets-shared/solid';
import Sub from './Sub';

// You can remove this one.
// If you don't want to use `tailwindcss` functionality.
import tailwindCssStyles from './tailwind.css';

const App = (props: any) => {
  // Use tailwind functionality.
  // You can remove this one.
  // If you don't want to use `tailwindcss` functionality.
  useStyles(tailwindCssStyles);

  const style = `.content p {
      margin-bottom: .7rem;
    }`;

  const [count, setCount] = createSignal(0);

  // If you didn't want to use `darkModeManager` feature,
  // then you have to remove the code below, 'cause it significantly increases the bundled file size.
  const darkModeManagerMisc = setupDarkModeManagerMisc();

  return (
    // If you didn't want to use `darkModeManager` feature,
    // then you have to remove the code below, 'cause it significantly increases the bundled file size.
    <DarkModeManagerContext.Provider value={darkModeManagerMisc}>
      <div class="content">
        {/** Inline styles. */}
        <style textContent={style} />
        {count() < 1 ? <Sub /> : null}
        <p>{count()}</p>
        <button
          class="bg-blue hover:bg-blue-900 rounded px-3.5 py-2 transition-all outline-0 shadow"
          onClick={() => setCount(count => count + 1)}
        >
          Click
        </button>
      </div>
    </DarkModeManagerContext.Provider>
  );
};

export default App;

// tools/widgets-cli/templates/lit/src/App.ts
import { html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import {
  DarkModeManagerReactiveController,
  LazyInjectStylesElement,
  provideDarkModeManager,
} from '@lenovo-it/widgets-shared/lit';

// You can remove this one.
// If you don't want to use `tailwindcss` functionality.
import tailwindcssStyles from './tailwind.css';

// Import the `Sub` and make it registered automatically.
import './components/Sub';

@customElement('$NAME$')
export class App extends LazyInjectStylesElement {
  // This property Could be removed if unnecessary.
  /** @see https://lit.dev/docs/components/styles/ */
  static styles = css`
    /** Some DOM intrinsic styles in css format. */
    p {
      color: blue;
    }
  `;

  get lazyInjectStyles() {
    return [
      // You can remove this one.
      // If you don't want to use `tailwindcss` functionality.
      tailwindcssStyles,
    ];
  }

  // If you didn't want to use `darkModeManager` feature,
  // then you have to remove the code below, 'cause it significantly increases the bundled file size.
  // Effective only under this format.
  @provideDarkModeManager()
  private darkModeManager = new DarkModeManagerReactiveController(this, {});

  @property()
  count = 1;

  handleCountIncrease() {
    this.count++;
  }

  render() {
    return html`
      <div class="$NAME$">
        <!-- Must not to write as the shorter one: '<$NAME$-sub />' -->
        <!-- That will cause unexpected issues! -->
        ${this.count < 10 ? html`<$NAME$-sub></$NAME$-sub>` : null}
        <p>${this.count}</p>
        <button @click="${this.handleCountIncrease}">Click</button>
      </div>
    `;
  }
}
